class Solution {
    public boolean canMakeSubsequence(String str1, String str2) {
        int n=str1.length();
        int m=str2.length();
        int idx=0;// for traversing str1..........starts from 0....
        int idx1=0;//for traversing str2...........starts from 0.....
        while(idx<n && idx1<m){
            char c1=str1.charAt(idx);//Stores char from s1 at idx...........
            char c2=str2.charAt(idx1);//Stores char from s2 at idx1.........
            if(c1==c2 || (c1 -'a'+1)%26==(c2 -'a'))idx1++;// converting c1 to integer and gives the next char of c1 Cyclicallyyy...........and converts c2 as an integer and checks the next char of c1 is matches to c2 we increment idx1...........to next char of s2
            idx++;// after checking increment idx to next char in s1........
        }
        return idx1==m;
    }
}